version: "3.9"

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: docker-test_php-fpm
    user: "www-data:www-data"
    volumes:
      - ./magento:/magento
