version: "3.9"

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        USER: 1000
    container_name: docker-test_php-fpm
    volumes:
      - ./magento:/magento